language: php

php:
  - 7.1

services:
  - docker

before_install:
  - make init

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build


after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

script:
  - make test

env:
  global:
    - CC_TEST_REPORTER_ID=0d582960fd679c13b185143381a4b908387d17fddf4509e2dedc3e3708a65c31